apiVersion: v1
kind: Service
metadata:
  name: quay-datastore
  labels:
    quay-component: quay-app
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: quay-datastore
    quay-component: quay-app
