apiVersion: quay.redhat.com.quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: skynet-quay
spec:
  configBundleSecret: quay-config-secret-abc123
  managedComponents:
    - kind: postgres
    - kind: clair
    - kind: redis
    - kind: storage
