apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
components:
  - ../components/postgres
  - ../components/redis
  - ../components/clair
# TODO(alecmerdler): Define patch which replaces `type: LoadBalancer` for Quay service for `ClusterIP` (just use `kubefwd` for access)
secretGenerator:
  - name: quay-config-secret
    behavior: merge
    files:
      - ./bundle/config.yaml
